-- AlterEnum
-- This migration adds more than one value to an enum.
-- With PostgreSQL versions 11 and earlier, this is not possible
-- in a single migration. This can be worked around by creating
-- multiple migrations, each migration adding only one value to
-- the enum.


ALTER TYPE "BankName" ADD VALUE 'AGRANI_SME_FINANCING_COMPANY_LIMITED';
ALTER TYPE "BankName" ADD VALUE 'AVIVA_FINANCE_LIMITED';
ALTER TYPE "BankName" ADD VALUE 'BD_FINANCE';
ALTER TYPE "BankName" ADD VALUE 'BANGLADESH_INDUSTRIAL_FINANCE_COMPANY_LIMITED';
ALTER TYPE "BankName" ADD VALUE 'BANGLADESH_INFRASTRUCTURE_FINANCE_FUND_LIMITED';
ALTER TYPE "BankName" ADD VALUE 'BAY_LEASING_AND_INVESTMENT_LIMITED';
ALTER TYPE "BankName" ADD VALUE 'CVC_FINANCE_LIMITED';
ALTER TYPE "BankName" ADD VALUE 'DBH_FINANCE_PLC';
ALTER TYPE "BankName" ADD VALUE 'FAREAST_FINANCE_AND_INVESTMENT_LIMITED';
ALTER TYPE "BankName" ADD VALUE 'FAS_FINANCE_AND_INVESTMENT_LIMITED';
ALTER TYPE "BankName" ADD VALUE 'FIRST_FINANCE_LIMITED';
ALTER TYPE "BankName" ADD VALUE 'GSP_FINANCE_COMPANY_LIMITED';
ALTER TYPE "BankName" ADD VALUE 'HAJJ_FINANCE_COMPANY_LIMITED';
ALTER TYPE "BankName" ADD VALUE 'IDLC_FINANCE_LIMITED';
ALTER TYPE "BankName" ADD VALUE 'IIDFC';
ALTER TYPE "BankName" ADD VALUE 'IDCOL';
ALTER TYPE "BankName" ADD VALUE 'INTERNATIONAL_LEASING_AND_FINANCIAL_SERVICES_LIMITED';
ALTER TYPE "BankName" ADD VALUE 'IPDC_FINANCE_LIMITED';
ALTER TYPE "BankName" ADD VALUE 'ISLAMIC_FINANCE_AND_INVESTMENT_LIMITED';
ALTER TYPE "BankName" ADD VALUE 'LANKABANGLA_FINANCE_LIMITED';
ALTER TYPE "BankName" ADD VALUE 'LANKAN_ALLIANCE_FINANCE_LIMITED';
ALTER TYPE "BankName" ADD VALUE 'MERIDIAN_FINANCE_AND_INVESTMENT_LIMITED';
ALTER TYPE "BankName" ADD VALUE 'MIDAS_FINANCING_LIMITED';
ALTER TYPE "BankName" ADD VALUE 'NAGAD_FINANCE_PLC';
ALTER TYPE "BankName" ADD VALUE 'NATIONAL_FINANCE_LIMITED';
ALTER TYPE "BankName" ADD VALUE 'NATIONAL_HOUSING_FINANCE_AND_INVESTMENTS_LIMITED';
ALTER TYPE "BankName" ADD VALUE 'PEOPLES_LEASING_AND_FINANCIAL_SERVICES_LIMITED';
ALTER TYPE "BankName" ADD VALUE 'PHOENIX_FINANCE_AND_INVESTMENTS_LIMITED';
ALTER TYPE "BankName" ADD VALUE 'PREMIER_LEASING_AND_FINANCE_LIMITED';
ALTER TYPE "BankName" ADD VALUE 'PRIME_FINANCE_AND_INVESTMENT_LIMITED';
ALTER TYPE "BankName" ADD VALUE 'SABINCO';
ALTER TYPE "BankName" ADD VALUE 'UAE_BANGLADESH_INVESTMENT_COMPANY_LIMITED';
ALTER TYPE "BankName" ADD VALUE 'UNION_CAPITAL_LIMITED';
ALTER TYPE "BankName" ADD VALUE 'UNITED_FINANCE_LIMITED';
ALTER TYPE "BankName" ADD VALUE 'UTTARA_FINANCE_AND_INVESTMENTS_LIMITED';
